#@ load("@ytt:data", "data")
---
apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: devx-container-platform-workshop
spec:
  title: Closing the Developer Experience Gap of Your Container Platforms
  description: A workshop that demonstrates how get started in building an application-aware platform that abstracts away all infrastructure specifics and fosters developer productivity.
  workshop:
    image: ghcr.io/timosalm/devx-container-platform-workshop:main
    files:
    - git:
        url: https://github.com/timosalm/devx-container-platform-workshop
        ref: origin/main
      includePaths:
      - /workshop/**
      - /samples/**
  session:
    namespaces:
      budget: custom
      role: view
      security:
        policy: restricted
    applications:
      console:
        enabled: false
      editor:
        enabled: true
      terminal:
        enabled: true
        layout: split
    env:
    - name: TAP_INGRESS
      value: #@ data.values.tap.ingress_domain
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: $(session_namespace)-session
        namespace: $(session_namespace)
      rules:
      - apiGroups: [""]
        resources: ["pods/portforward","pods/exec"]
        verbs: ['*']
      - apiGroups: [""]
        resources: [namespaces, serviceaccounts]
        verbs: [patch]
      - apiGroups: [kpack.io]
        resources: [images]
        verbs: ['*']
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: $(session_namespace)-session-rb
        namespace: $(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: $(session_namespace)-session
      subjects:
        - kind: ServiceAccount
          namespace: $(workshop_namespace)
          name: $(service_account)